#!/bin/sh

# This script does the following:
#	Run by itself, set the wallpaper (at X start).
#	If given a file, set that as the new wallpaper.
#	If given a directory, choose random file in it.
#	If wal is installed, also generates a colorscheme.

# Location of link to wallpaper link.
#bgloc="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"
bgloc_1="${XDG_DATA_HOME:-$HOME/.local/share/}/bg1"
bgloc_2="${XDG_DATA_HOME:-$HOME/.local/share/}/bg2"

# Configuration files of applications that have their themes changed by pywal.
#dunstconf="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc"
#zathuraconf="${XDG_CONFIG_HOME:-$HOME/.config}/zathura/zathurarc"

# Get all possible displays
allposs=$(xrandr -q | grep "connected")

# Get all connected screens.
screens=$(echo "$allposs" | awk '/ connected/ {print $1}')
screen_pri=$(echo "$screens" | grep "HDMI")
screen_sub=$(echo "$screens" | grep "DP")
num_actived_monitor=$(xrandr --listactivemonitors | grep Monitors | awk '{print $2}')

trueloc_1="$(readlink -f "$1")" &&
case "$(file --mime-type -b "$trueloc_1")" in
	image/* ) ln -sf "$(readlink -f "$1")" "$bgloc_1" ;;
	inode/directory ) ln -sf "$(find "$trueloc_1" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc_1" && [ "$num_actived_monitor" -gt 1 ] &&  ln -sf "$(find "$trueloc_1" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc_2";;
	*) notify-send "Error" "Not a valid image." ; exit 1;;
esac

# set wallpaper for multi-monitor
[ "$num_actived_monitor" -gt 1 ] && trueloc_2="$(readlink -f "$2")" &&
case "$(file --mime-type -b "$trueloc_2")" in
	image/* ) ln -sf "$(readlink -f "$1")" "$bgloc_2" ;;
	inode/directory ) ln -sf "$(find "$trueloc_2" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc_2" ;;
	*) notify-send "Error" "Not a valid image." ; exit 1;;
esac
# If pywal is installed, use it.
#if command -v wal >/dev/null 2>&1 ; then
	#wal -i "$(readlink -f $bgloc_1)" -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" >/dev/null 2>&1 &&
	#pidof dwm >/dev/null && xdotool key super+F12
## If pywal is removed, return config files to normal.
#else
	#[ -f "$dunstconf.bak" ] && unlink "$dunstconf" && mv "$dunstconf.bak" "$dunstconf"
	#[ -f "$zathuraconf.bak" ] && unlink "$zathuraconf" && mv "$zathuraconf.bak" "$zathuraconf"
#fi

#feh --no-fehbg --recursive --randomize --bg-fill "$bgloc"
# If there's only one screen
[ "$num_actived_monitor" -lt 2 ] && xwallpaper --zoom "$bgloc_1" && rm -f "$bgloc_2" && exit 0
xwallpaper --output "$screen_pri" --zoom "$bgloc_1"
xwallpaper --output "$screen_sub" --zoom "$bgloc_2"
